### ISSUE TITLE
QoL Suggestion: Copying the generated image to the clipboard

### ISSUE THREAD

**Issue by grizzogor** [logankuzyk/shareddit#4]
Hi, my community on Discord likes to use Shareddit as a way to show Reddit threads and comments as an image. Is it possible to have the generated image be attached to the clipboard? This will help in the Quality of Life of the program, as the user doesn't need to save the image to their disk in order to share it.

Thanks,
grizzogor

**Comment by logankuzyk** [comment]
Thanks for opening an issue! That sounds like a good addition, I will try and implement the new feature within the next week.

**Comment by logankuzyk** [comment]
@ian70203 I've just created a basic Discord bot for shareddit.

If you want to try it out, feel free to add it to your server: https://discord.com/api/oauth2/authorize?client_id=946118696231895140&permissions=35840&scope=bot%20applications.commands

The repository is available at: https://github.com/logankuzyk/shareddit-discord

Please let me know what you think! I've submitted it to top.gg but it will take a few weeks to get verified.
